# Generated by Django 2.1.4 on 2019-12-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='user_id',
        ),
    ]
